### ISSUE TITLE
24620204_Angel_Garcia_infografia

### ISSUE THREAD

**Issue by ANGELGARCIASANTIAGO** [SistemasTecTlaxiaco/infografia-ANGELGARCIASANTIAGO#1]
``

**Comment by ANGELGARCIASANTIAGO** [comment]
[24620204_Angel_Garcia_infografia.pdf](https://github.com/user-attachments/files/16738378/24620204_Angel_Garcia_infografia.pdf)

**Comment by ANGELGARCIASANTIAGO** [comment]
Luis Angel García Santiago_1AS_24620204

**Comment by Eddi3mendoz** [comment]
Redacción y Ortografía:14/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:14/14
Referencias:10/14
Presentación:14/14
Calificación Final : 19.2/20
Califico: Edwin Eduardo Mendoza Cruz
